version: "1.0"

services:
  backend:
    build: 
      context: ./back-end
    ports:
      - "8080:8080"
    volumes:
      - ./back-end/prisma/dev.db:/app/prisma/dev.db
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
  # frontend:
  #   build: 
  #     context: ./front-end
  #   ports:
  #     - "80:80"
  #   environment:
  #     - GOOGLE_API_KEY=${GOOGLE_API_KEY}